# Generated by Django 5.2.8 on 2025-11-14 19:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Szerző neve')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Életrajz')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Cím')),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='ISBN szám')),
                ('publication_year', models.IntegerField(blank=True, null=True, verbose_name='Kiadás éve')),
                ('cover_image_url', models.URLField(blank=True, null=True, verbose_name='Borítókép URL')),
                ('authors', models.ManyToManyField(related_name='books', to='books.author', verbose_name='Szerző(k)')),
            ],
        ),
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('TR', 'Olvasni fogom'), ('RG', 'Éppen olvasom'), ('RD', 'Elolvasva')], default='TR', max_length=2, verbose_name='Státusz')),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Értékelés (1-5)')),
                ('private_notes', models.TextField(blank=True, null=True, verbose_name='Személyes jegyzetek')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_entries', to='books.book', verbose_name='Könyv')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_books', to=settings.AUTH_USER_MODEL, verbose_name='Felhasználó')),
            ],
            options={
                'unique_together': {('user', 'book')},
            },
        ),
    ]
